# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

r_binary_packages:
  - XML
  - shiny
  
r_packages:
  - gistr
  - RSelenium
  - rmarkdown

r_github_packages:
  - tdhock/ggplot2
  - yihui/servr

notifications:
  email:
    on_success: change
    on_failure: change
