# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  # Basic dependencies for using animint installing/testing animint
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github tdhock/ggplot2
  # Dependencies for shiny/rmarkdown integration
  # Thanks RStudio! https://github.com/rstudio/rmarkdown/blob/master/.travis.yml
  # Install binary pandoc from Rstudio 
  - mkdir -p $HOME/opt/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
    -d $HOME/opt/pandoc
  - chmod +x $HOME/opt/pandoc/pandoc*
  - rm pandoc-1.12.3.zip
  - $HOME/opt/pandoc/pandoc --version
  # Dependencies for running animint tests
  - ./travis-tool.sh r_binary_install servr
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install shiny
  # Binary install of rmarkdown doesn't work (currently?)
  - ./travis-tool.sh install_github rstudio/rmarkdown
  - ./travis-tool.sh install_github ropensci/RSelenium

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
